import { b, rich } from "./demo-blocks";
import { type GuideSeed, sources, link } from "./demo-guides-stacks-shared";

/**
 * Four "should you build here" platform evaluations — Squarespace, Substack,
 * beehiiv, Webflow. Written in first person, sourced inline. Filed under the
 * existing "own-your-stack" hub alongside the migration guides.
 */
export const EVALUATIONS: GuideSeed[] = [
  {
    slug: "should-you-use-squarespace",
    title: "Should you build on Squarespace?",
    data: {
      tagline: "What you actually get, what it costs, and what you don't own",
      summary: "Pricing, hosting, custom code, and lock-in risk for Squarespace — including who owns it now — reviewed before you build on it.",
      category: "own-your-stack",
      source_platform: "squarespace",
      target_platform: "",
      difficulty: "beginner",
      effort_hours_min: 0,
      effort_hours_max: 0,
      cost_min_usd: 16,
      cost_max_usd: 139,
      cost_period: "mo",
      tags: ["website-builder", "platform-evaluation"],
      resource_slugs: [],
      skills_required: [],
      requirements: [],
    },
    blocks: [
      b("heading", { text: "Should you build on Squarespace?", level: "h1", align: "left" }),
      rich("<p>I get asked about Squarespace a lot, usually by someone who wants a site up this weekend and doesn't want to think about servers. It's a fine answer to that question. It's a closed answer to every question after that one: no database you control, no self-hosting, and a broad content license in the fine print. Here's what I found when I actually read the terms.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "No free tier — a 14-day trial only, and the site stays unpublished until you pay",
        "Basic: $16/mo billed yearly — blogs, portfolios, small business sites",
        "Core: $23/mo — unlocks ecommerce basics and full Code Injection",
        "Plus: $39/mo, Advanced: $99/mo — bigger stores, more automation",
        "Paying month-to-month instead of yearly runs noticeably higher, up to $139/mo on Advanced",
      ] }),
      b("heading", { text: "Hosting and database", level: "h2", align: "left" }),
      rich("<p>Squarespace hosts everything itself. There's no supported way to self-host a Squarespace site, and no database you can query directly. It isn't a headless CMS the way Webflow is — content and delivery aren't separated. A paid Developer Platform tier exposes pages as JSON for narrow read access, but that's a long way from owning your data.</p>"),
      b("heading", { text: "Custom code", level: "h2", align: "left" }),
      rich("<p>CSS is editable on every plan. Full Code Injection — custom HTML and JavaScript in the header or footer — needs Core plan or higher. If you're planning to point any of this at an external CMS or API, budget for at least Core.</p>"),
      b("heading", { text: "What you don't own", level: "h2", align: "left" }),
      b("callout", { tone: "warning", title: "The license you grant them", body: "Publishing to Squarespace means granting them a broad license in the fine print — a non-exclusive, worldwide, perpetual, irrevocable, royalty-free right to host, reproduce, modify, and distribute what you post, plus a separate right to feature your site in their own marketing. Native export only pulls posts, pages, and media as XML; your design, template, and custom code stay behind." }),
      b("callout", { tone: "info", title: "Who owns it now", body: "Squarespace went private in October 2024 — Permira bought it for about $7.2B after its first offer was rejected by shareholders. Founder Anthony Casalena stayed on as CEO. It's no longer a public company, which means no quarterly earnings call keeping it accountable to anyone outside Permira's boardroom." }),
      b("heading", { text: "My verdict", level: "h2", align: "left" }),
      b("callout", { tone: "tip", title: "Where I land", body: "I'd use Squarespace for a marketing page I planned to rebuild within a year anyway. I wouldn't build anything I cared about owning — a blog with a real subscriber list, a store, a tool — on a platform that can't hand my own data back to me in a usable form." }),
      sources([
        link("https://www.squarespace.com/pricing", "Squarespace Pricing"),
        link("https://support.squarespace.com/hc/en-us/articles/206545717-Squarespace-Developer-Platform-FAQ", "Squarespace Developer Platform FAQ"),
        link("https://support.squarespace.com/hc/en-us/articles/205815908-Using-code-injection", "Using code injection"),
        link("https://support.squarespace.com/hc/en-us/articles/206566687-Exporting-your-site", "Exporting your site"),
        link("https://www.squarespace.com/terms-of-service/", "Squarespace Terms of Service"),
        link("https://www.permira.com/news-and-insights/announcements/squarespace-to-go-private-in-69bn-all-cash-transaction-with-permira", "Permira: Squarespace to go private"),
        link("https://techcrunch.com/2024/10/17/permira-completes-squarespace-acquisition-after-upping-bid-to-7-2b/", "TechCrunch: Permira completes Squarespace acquisition"),
      ]),
    ],
  },
  {
    slug: "should-you-use-substack",
    title: "Should you build on Substack?",
    data: {
      tagline: "Free to start, a real 10% cut, and almost nothing you can customize",
      summary: "What Substack actually costs once you charge subscribers, what you can't customize, and the moderation record worth knowing before you build there.",
      category: "own-your-stack",
      source_platform: "substack",
      target_platform: "",
      difficulty: "beginner",
      effort_hours_min: 0,
      effort_hours_max: 0,
      cost_min_usd: 0,
      cost_max_usd: 0,
      cost_period: "mo",
      tags: ["newsletter", "platform-evaluation"],
      resource_slugs: [],
      skills_required: [],
      requirements: [],
    },
    blocks: [
      b("heading", { text: "Should you build on Substack?", level: "h1", align: "left" }),
      rich("<p>Substack is the easiest newsletter I know how to start — free, no code, live in ten minutes. It's also the platform I'd think hardest about before routing paying subscribers through it, and not only because of the fee. Here's the full picture.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Free to publish at any scale as long as you don't charge for subscriptions",
        "Paid subscriptions: a flat 10% platform fee on top of Stripe's own ~2.9% + $0.30 — unchanged since 2017",
        "A $10/mo subscriber nets you about $8.40 after both cuts",
        "The old Substack Pro cash-advance program is closed to new writers; Enterprise pricing is sales-led and unpublished",
      ] }),
      b("heading", { text: "Hosting and customization", level: "h2", align: "left" }),
      rich("<p>You get a free yourname.substack.com address, or a custom domain for a one-time $50 fee. There's no self-hosting option, no database, and no custom CSS, HTML, or JavaScript at any tier — code blocks render as plain text, not executable code. Custom iframe embeds are blocked outside a short allowlist.</p>"),
      b("heading", { text: "The part most people don't check", level: "h2", align: "left" }),
      b("callout", { tone: "warning", title: "No real API", body: "Substack's public 'Developer API' only returns profile data tied to a linked LinkedIn handle — it isn't a content or CMS integration API. There's no supported way to sync Substack with an external database or CMS; anything close relies on unofficial, reverse-engineered tooling." }),
      b("callout", { tone: "info", title: "Export is real, the reputation risk isn't", body: "You can export your posts and subscriber list as a zip/CSV any time, so you're not locked in technically. The reason writers keep leaving anyway: in November 2023, The Atlantic identified over a dozen newsletters using overt Nazi symbols monetizing on the platform, plus dozens more far-right extremist newsletters. Substack removed only a handful of accounts in January 2024 without changing its underlying moderation policy — a follow-up investigation found roughly 75 similar newsletters still monetizing." }),
      b("heading", { text: "My verdict", level: "h2", align: "left" }),
      b("callout", { tone: "tip", title: "Where I land", body: "I'd start a free newsletter here to test an idea fast — export is real, so the downside is low. I wouldn't build a paid publication I depended on financially here: the 10% fee compounds forever, there's no way to make the reader experience your own, and the platform's moderation record is now part of what you're associated with by being on it." }),
      sources([
        link("https://support.substack.com/hc/en-us/articles/360051222571-How-do-I-set-up-my-custom-domain-on-Substack", "Substack: custom domain setup"),
        link("https://support.substack.com/hc/en-us/articles/360037463152-Can-I-edit-the-CSS-or-HTML-on-Substack", "Can I edit the CSS or HTML on Substack?"),
        link("https://support.substack.com/hc/en-us/articles/45099095296916-Substack-Developer-API", "Substack Developer API"),
        link("https://support.substack.com/hc/en-us/articles/360037466012-How-do-I-export-my-posts", "How do I export my posts"),
        link("https://techcrunch.com/2024/01/09/substack-nazi-content-policies-controversy/", "TechCrunch: Substack's Nazi content policy controversy"),
        link("https://freespeechproject.georgetown.edu/tracker-entries/substack-decision-to-remove-nazi-accounts-leads-to-outcry-over-censorship/", "Georgetown Free Speech Project tracker"),
      ]),
    ],
  },
  {
    slug: "should-you-use-beehiiv",
    title: "Should you build on beehiiv?",
    data: {
      tagline: "The Substack alternative built to compete on ownership terms — mostly",
      summary: "beehiiv's pricing, its real API, and what to know about its leadership before you build a paid newsletter there.",
      category: "own-your-stack",
      source_platform: "beehiiv",
      target_platform: "",
      difficulty: "beginner",
      effort_hours_min: 0,
      effort_hours_max: 0,
      cost_min_usd: 0,
      cost_max_usd: 419,
      cost_period: "mo",
      tags: ["newsletter", "platform-evaluation"],
      resource_slugs: [],
      skills_required: [],
      requirements: [],
    },
    blocks: [
      b("heading", { text: "Should you build on beehiiv?", level: "h1", align: "left" }),
      rich("<p>beehiiv is what a lot of writers reach for specifically because Substack burned them. It's the strongest technical fit of the newsletter platforms I've looked at — a real API, 0% platform fee once you're paying — but it's still a small VC-backed company, and 2026 gave me a reason to say that plainly.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Launch (free) — up to 2,500 subscribers, unlimited sends, custom domain, no monetization",
        "Scale — roughly $49/mo under 1,000 subscribers up to $329/mo at 100,000 — unlocks monetization at 0% platform fee (Stripe's own cut still applies)",
        "Max — roughly $109–$419/mo — removes branding, adds a sponsorship storefront and custom HTML blocks (beta)",
      ] }),
      b("heading", { text: "Hosting, database, and the API", level: "h2", align: "left" }),
      rich("<p>Like Substack, it's a closed hosted platform — no self-hosting, no database you control. Where it pulls ahead: a real, documented API (developers.beehiiv.com) for creating and reading posts and managing subscribers. If I were wiring a newsletter platform up to an external CMS, this is the one I'd reach for first — everything else here is 'push a finished draft over,' not real integration.</p>"),
      b("heading", { text: "Custom code", level: "h2", align: "left" }),
      rich("<p>Basic HTML in a post is fine, but script and style tags get stripped. Full custom HTML blocks for site customization exist in beta, gated to the Max and Enterprise plans.</p>"),
      b("heading", { text: "What I'd want you to know before signing up", level: "h2", align: "left" }),
      b("callout", { tone: "info", title: "Export is clean", body: "Post content and subscriber data, including custom fields, export as CSV any time — the platform doesn't lock your list in." }),
      b("callout", { tone: "warning", title: "The CEO's May 2026 endorsement", body: "In May 2026, beehiiv cofounder and CEO Tyler Denk publicly endorsed Spencer Pratt — the reality-TV star running a MAGA-aligned campaign for LA mayor — on his personal Instagram, and stood by it when a journalist's screenshot went viral rather than walking it back. It was a personal endorsement, not a company statement, and beehiiv has no shared discovery feed or leaderboard the way Substack does, so it doesn't route reader attention the way Substack founders' politics can. Still worth knowing whose company you're building a list inside." }),
      b("heading", { text: "My verdict", level: "h2", align: "left" }),
      b("callout", { tone: "tip", title: "Where I land", body: "Of the two newsletter platforms here, I'd pick beehiiv over Substack for a paid publication — the API is real, the fee structure rewards you for growing, and export is clean. It's still a small, VC-backed company a few years from its next fundraise or acquisition, so keep your list exported and don't treat any hosted newsletter tool as permanent infrastructure." }),
      sources([
        link("https://www.beehiiv.com/pricing", "beehiiv Pricing"),
        link("https://www.beehiiv.com/support/article/4413248700439-using-html-in-beehiiv-posts", "Using HTML in beehiiv posts"),
        link("https://developers.beehiiv.com/api-reference/posts/create", "beehiiv API Reference: Posts"),
        link("https://www.beehiiv.com/support/article/12258595483543-exporting-post-content-or-subscriber-data-from-beehiiv", "Exporting post content or subscriber data"),
        link("https://www.revenuerulebreaker.com/beehiivs-ceo-backs-a-maga-candidate-but-dont-pack-your-bags-just-yet/", "Revenue Rulebreaker: beehiiv's CEO backs a MAGA candidate (May 13, 2026)"),
        link("https://www.nea.com/blog/nea-founder-forward-qa-with-beehiivs-tyler-denk", "NEA Q&A with Tyler Denk"),
      ]),
    ],
  },
  {
    slug: "should-you-use-webflow",
    title: "Should you build on Webflow?",
    data: {
      tagline: "The most technically real of the four, and the one worth actually integrating",
      summary: "Webflow's pricing, its real CMS and API, and the export gap worth knowing before you build production infrastructure on it.",
      category: "own-your-stack",
      source_platform: "webflow",
      target_platform: "",
      difficulty: "beginner",
      effort_hours_min: 0,
      effort_hours_max: 0,
      cost_min_usd: 0,
      cost_max_usd: 2500,
      cost_period: "mo",
      tags: ["website-builder", "platform-evaluation"],
      resource_slugs: [],
      skills_required: [],
      requirements: [],
    },
    blocks: [
      b("heading", { text: "Should you build on Webflow?", level: "h1", align: "left" }),
      rich("<p>Webflow is the only platform in this set I'd call a real visual builder with a real CMS — Collections and Items, a documented API, code export. It's also the most expensive to run at scale, and the company just went through a rough stretch. Here's the honest breakdown.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Starter (free) — 1 site, webflow.io subdomain, 2 pages, 20 CMS collections, 50 items",
        "Basic — $15/mo yearly — 300 static pages, no CMS",
        "Premium (CMS + Business merged) — $25/mo yearly, $39/mo monthly — up to 20,000 CMS items, 40 collections",
        "Team — $2,500/mo on an annual contract — 10 seats, 100 collections, localization",
      ] }),
      b("heading", { text: "Hosting and database", level: "h2", align: "left" }),
      rich("<p>Webflow runs on AWS behind Cloudflare's CDN. You can export static HTML/CSS/JS and host it yourself, but full custom hosting — publishing straight to your own AWS, Azure, or GitHub Pages — is Enterprise-only. The CMS itself (Collections/Items) is real and structured, closer to a headless CMS than anything else here, but there's no native two-way sync to an external database like Supabase — you'd build that yourself against their Data API.</p>"),
      b("heading", { text: "Custom code and API", level: "h2", align: "left" }),
      rich("<p>Full HTML/CSS/JS injection is supported on any paid plan (not the free Starter tier), capped at 50,000 characters per field. The public Data API covers sites, CMS content, forms, and orders — documented, OAuth-based, 60 requests/minute. If I were pushing content from an external CMS into a marketing site, Webflow's API is the one I'd trust to hold up.</p>"),
      b("heading", { text: "The catch", level: "h2", align: "left" }),
      b("callout", { tone: "warning", title: "CMS content doesn't export", body: "Static export explicitly excludes CMS content — meaning once you've built out Collections full of real content, you can't cleanly get it back out. Migrating off a CMS-driven Webflow site usually means scraping your own pages or rebuilding by hand." }),
      b("callout", { tone: "info", title: "A company mid-pivot", body: "Webflow laid off about 8% of staff in July 2024, then went through a larger restructuring in May 2026 tied to a strategy pivot toward 'agentic web' AI tooling under new CEO Linda Tong. No acquisition or ownership change has happened — it's still private, last valued around $4B in 2022 — but it's a company mid-pivot, not a settled one." }),
      b("heading", { text: "My verdict", level: "h2", align: "left" }),
      b("callout", { tone: "tip", title: "Where I land", body: "Webflow is the one platform here I'd actually build production marketing infrastructure on, specifically because the API and CMS are real enough to integrate with something like Supabase properly. I'd still keep the CMS content itself backed up outside Webflow — the export gap means you don't fully own it until you've built that backup yourself." }),
      sources([
        link("https://help.webflow.com/hc/en-us/articles/51059955082387-Updated-pricing-and-simplified-plans-for-May-2026", "Webflow: updated pricing, May 2026"),
        link("https://webflow.com/hosting", "Webflow Hosting"),
        link("https://help.webflow.com/hc/en-us/articles/33961357265299-Custom-code-in-head-and-body-tags", "Custom code in head and body tags"),
        link("https://developers.webflow.com/data/docs/data-clients", "Webflow Data API docs"),
        link("https://help.webflow.com/hc/en-us/articles/33961386739347-How-do-I-export-my-Webflow-site-code", "How do I export my Webflow site code"),
        link("https://webflow.com/blog/restructuring-announcement", "Webflow restructuring announcement"),
      ]),
    ],
  },
];
