import { b, rich } from "./demo-blocks";
import { type GuideSeed, sources, link } from "./demo-guides-stacks-shared";

/** Stack-deploy guides, part A: Vercel+Supabase, Vercel+Neon, DigitalOcean+Supabase. */
export const DEPLOY_A: GuideSeed[] = [
  {
    slug: "deploy-on-vercel-and-supabase",
    title: "Deploy on Vercel + Supabase",
    data: {
      tagline: "The fastest path from git push to a live site with a real Postgres database",
      summary: "Fact-checked pricing, feasibility, and a full deploy walkthrough for Vercel hosting paired with Supabase as your database, auth, and storage backend.",
      category: "own-your-stack",
      source_platform: "vercel",
      target_platform: "supabase",
      difficulty: "beginner",
      effort_hours_min: 2,
      effort_hours_max: 4,
      cost_min_usd: 0,
      cost_max_usd: 45,
      cost_period: "mo",
      tags: ["hosting", "database", "platform-evaluation"],
      resource_slugs: [],
      skills_required: ["Basic git", "Comfortable with environment variables"],
      requirements: ["A GitHub/GitLab repo", "A domain if you want a custom one"],
    },
    blocks: [
      b("heading", { text: "Deploy on Vercel + Supabase", level: "h1", align: "left" }),
      rich("<p>This is the stack I'd point most people to first. Push to git, Vercel builds and deploys automatically, and Supabase gives you a real Postgres database with auth and file storage bundled in. Both have real free tiers, so you can build the whole thing before paying anything.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Vercel Hobby: free, but for non-commercial use only — 100GB transfer, 1M edge requests, 1M function invocations",
        "Vercel Pro: $20/seat/mo + $20 usage credit, 1TB transfer, then $0.15/GB overage",
        "Supabase Free: 500MB database, 50K monthly active users, 1GB storage, 5GB egress, pauses after 7 days of no database activity",
        "Supabase Pro: from $25/mo — 8GB database, 100K MAUs, 100GB storage, includes a $10/mo compute credit",
        "Realistic small-app total once you outgrow free tiers: roughly $45/mo (Vercel Pro + Supabase Pro)",
      ] }),
      b("callout", { tone: "danger", title: "Read this before you launch", body: "Vercel's bandwidth overage isn't hard-capped on Pro. In 2025–2026, people reported real bill shock from bot traffic and DDoS — one $23,000 bill from DDoS traffic, another site hit $1,477 (mostly overage) from bots crawling before it had even launched publicly. Set up Spend Management alerts before you go live, and know that alerts have reportedly failed to stop a fast spike at least once." }),
      b("heading", { text: "Feasibility", level: "h2", align: "left" }),
      rich("<p>This is the easiest full-stack deploy in this set. If you can run <code>git push</code> and paste an environment variable, you can do this in an afternoon.</p>"),
      b("heading", { text: "Deploy it", level: "h2", align: "left" }),
      rich("<p>Create a Supabase project, grab your connection string, and set it as an environment variable in Vercel. Because Vercel functions are serverless — a new connection can spin up per request — use Supabase's pooled connection string (Supavisor), not the direct one, or you'll exhaust your connection limit under any real traffic.</p>"),
      b("code", { filename: ".env.local", language: "bash", code: "# Use the pooled (Supavisor) connection string, not the direct one\nDATABASE_URL=postgresql://postgres.[project-ref]:[password]@aws-0-[region].pooler.supabase.com:6543/postgres\nNEXT_PUBLIC_SUPABASE_URL=https://[project-ref].supabase.co\nNEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ..." }),
      b("code", { filename: "terminal", language: "bash", code: "npm i -g vercel\nvercel link\nvercel env pull .env.local\nvercel --prod" }),
      b("callout", { tone: "tip", title: "Custom domain", body: "Domains work on every Vercel plan, including Hobby. Point an apex domain at Vercel's A record, or a subdomain via CNAME, in your DNS provider — propagation can take up to 24 hours." }),
      b("heading", { text: "Go-live checklist", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Connection string uses the pooled endpoint, not the direct one",
        "Spend Management / usage alerts configured on Vercel",
        "Supabase project confirmed on Pro if you need it to never auto-pause",
        "Custom domain DNS propagated and SSL issued",
      ] }),
      sources([
        link("https://vercel.com/docs/plans/hobby", "Vercel Hobby Plan docs"),
        link("https://vercel.com/pricing", "Vercel Pricing"),
        link("https://vercel.com/docs/limits/fair-use-guidelines", "Vercel Fair Use Guidelines"),
        link("https://supabase.com/pricing", "Supabase Pricing"),
        link("https://supabase.com/docs/guides/platform/free-project-pausing", "Supabase free project pausing"),
        link("https://usagebox.com/articles/vercel-23000-dollar-bill-usage-based-platform-bill-shock-2026", "Vercel $23,000 bill report"),
        link("https://deploybase.app/blog/vercel-bill-shock-1100-bandwidth-costs-alternatives-2026", "Vercel bandwidth bill-shock reports, 2026"),
      ]),
    ],
  },
  {
    slug: "deploy-on-vercel-and-neon",
    title: "Deploy on Vercel + Neon",
    data: {
      tagline: "Serverless hosting paired with serverless Postgres — a database branch for every preview deploy",
      summary: "Fact-checked pricing, feasibility, and a full deploy walkthrough for Vercel hosting paired with Neon's branching serverless Postgres.",
      category: "own-your-stack",
      source_platform: "vercel",
      target_platform: "neon",
      difficulty: "beginner",
      effort_hours_min: 2,
      effort_hours_max: 4,
      cost_min_usd: 0,
      cost_max_usd: 40,
      cost_period: "mo",
      tags: ["hosting", "database", "platform-evaluation"],
      resource_slugs: [],
      skills_required: ["Basic git", "Comfortable with environment variables"],
      requirements: ["A GitHub/GitLab repo", "A domain if you want a custom one"],
    },
    blocks: [
      b("heading", { text: "Deploy on Vercel + Neon", level: "h1", align: "left" }),
      rich("<p>Vercel actually shut down its own \"Vercel Postgres\" product in 2025 and rebuilt it on top of Neon — so this pairing is closer to native than it looks. The standout feature: Neon gives every preview deployment its own instant, copy-on-write database branch, seeded with real data, that gets cleaned up automatically.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Vercel Hobby: free (non-commercial only), Pro: $20/seat/mo + $20 usage credit",
        "Neon Free: 100 compute-hours/project/month, 0.5GB storage/project, 10 branches/project, mandatory scale-to-zero after 5 minutes idle",
        "Neon Launch: usage-based, $0.106/compute-hour, storage at $0.35/GB-month, no monthly minimum",
        "Extra database branches beyond the included quota: $1.50/branch-month",
        "Neon is now owned by Databricks (acquired May 2025, ~$1B) and rebranded internally as 'Lakebase' — still runs under its own pricing and branding",
      ] }),
      b("heading", { text: "Feasibility", level: "h2", align: "left" }),
      rich("<p>Just as easy as Vercel+Supabase to get running. The branching setup takes a little more configuration if you want preview-deploy branches wired up, but the default single-database setup is a five-minute job.</p>"),
      b("heading", { text: "Deploy it", level: "h2", align: "left" }),
      rich("<p>Add the Neon integration from the Vercel Marketplace (or connect manually) — it can auto-create a database branch named after each git branch and inject the connection string as a preview-scoped environment variable automatically.</p>"),
      b("code", { filename: ".env.local", language: "bash", code: "# Use the UNPOOLED connection string for migrations/pg_dump, pooled for the app\nDATABASE_URL=postgresql://[user]:[password]@[endpoint].neon.tech/[dbname]?sslmode=require" }),
      b("code", { filename: "terminal", language: "bash", code: "# Migrating an existing Postgres dump into Neon\npg_dump -Fc --no-tablespaces --no-owner --no-acl -d $OLD_DATABASE_URL -f backup.dump\npg_restore -d $NEON_UNPOOLED_URL backup.dump" }),
      b("callout", { tone: "warning", title: "Pooled vs. unpooled", body: "Use the unpooled connection string for pg_dump/pg_restore — pooled connections break dumps. Use the pooled string for the running app so serverless functions don't exhaust your connection limit." }),
      b("heading", { text: "Go-live checklist", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "App uses the pooled connection string, migrations use the unpooled one",
        "Preview-branch integration configured if you want per-PR databases",
        "Confirmed which tier you're on before a traffic spike hits compute-hour limits",
        "Custom domain DNS propagated and SSL issued",
      ] }),
      sources([
        link("https://vercel.com/pricing", "Vercel Pricing"),
        link("https://neon.com/pricing", "Neon Pricing"),
        link("https://neon.com/blog/new-usage-based-pricing", "Neon: new usage-based pricing"),
        link("https://neon.com/blog/neon-vercel-native-integration", "Neon: Vercel-native integration"),
        link("https://neon.com/docs/import/migrate-from-postgres", "Neon: migrate from Postgres"),
        link("https://www.databricks.com/blog/databricks-neon", "Databricks: acquiring Neon"),
        link("https://techcrunch.com/2025/05/14/databricks-to-buy-open-source-database-startup-neon-for-1b/", "TechCrunch: Databricks buys Neon for $1B"),
      ]),
    ],
  },
  {
    slug: "deploy-on-digitalocean-and-supabase",
    title: "Deploy on DigitalOcean + Supabase",
    data: {
      tagline: "A middle path — real infrastructure control without running your own database",
      summary: "Fact-checked pricing, feasibility, and a full deploy walkthrough for DigitalOcean App Platform or a Droplet, paired with Supabase.",
      category: "own-your-stack",
      source_platform: "digitalocean",
      target_platform: "supabase",
      difficulty: "intermediate",
      effort_hours_min: 4,
      effort_hours_max: 8,
      cost_min_usd: 5,
      cost_max_usd: 75,
      cost_period: "mo",
      tags: ["hosting", "database", "platform-evaluation"],
      resource_slugs: [],
      skills_required: ["Comfortable in a terminal", "Basic Linux/Docker familiarity if using a Droplet"],
      requirements: ["A GitHub repo (App Platform) or an SSH key (Droplet)", "A domain"],
    },
    blocks: [
      b("heading", { text: "Deploy on DigitalOcean + Supabase", level: "h1", align: "left" }),
      rich("<p>DigitalOcean sits between Vercel's fully-managed simplicity and running your own VPS. App Platform gives you git-push deploys with predictable flat pricing (no bandwidth bill shock like Vercel); a plain Droplet gives you full control if you want it. Either way, Supabase stays your database so you're not also running Postgres yourself.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "App Platform free tier: 3 static sites, 1GiB transfer/app/month",
        "App Platform paid: from $5/mo (1 vCPU, 512MB RAM, 50GB transfer) up to $50/mo (2 vCPU, 4GB RAM)",
        "Droplets: from $4/mo (1 vCPU, 512MB RAM) up to $24/mo (2 vCPU, 4GB RAM) — billed per-second since January 2026",
        "DigitalOcean Managed Postgres, if you skip Supabase: single-node from $15/mo (no failover, dev/test only), HA (primary + standby) from ~$60/mo total",
        "Supabase: same free/Pro tiers as the Vercel pairing above",
        "Bandwidth overage: $0.01/GiB on Droplets, $0.02/GiB pooled on App Platform",
      ] }),
      b("heading", { text: "Feasibility", level: "h2", align: "left" }),
      rich("<p>App Platform is close to Vercel-easy — git push, done. A bare Droplet is a real step up: you're installing Node, running the app under PM2, and fronting it with Nginx yourself. Budget a real afternoon if you've never set up a Droplet before, less if you stick to App Platform.</p>"),
      b("heading", { text: "Deploy it — App Platform (recommended for most people)", level: "h2", align: "left" }),
      rich("<p>Connect your GitHub repo in the App Platform dashboard, set your Supabase connection string as an encrypted environment variable, and DigitalOcean builds and redeploys on every push.</p>"),
      b("heading", { text: "Deploy it — Droplet (full control)", level: "h2", align: "left" }),
      b("code", { filename: "terminal", language: "bash", code: "# On a fresh Droplet\nsudo apt update && sudo apt install -y nodejs npm nginx\nnpm i -g pm2\ngit clone <your-repo> app && cd app\nnpm ci && npm run build\npm2 start npm --name app -- start\npm2 startup && pm2 save" }),
      b("code", { filename: "/etc/nginx/sites-available/app", language: "nginx", code: "server {\n  listen 80;\n  server_name yourdomain.com;\n  location / {\n    proxy_pass http://localhost:3000;\n    proxy_set_header Host $host;\n  }\n}" }),
      b("callout", { tone: "warning", title: "A Droplet is unmanaged", body: "There's no automatic patching, no managed SSL renewal, no automatic restarts on crash beyond what PM2 gives you. If that sounds like more than you want to own, use App Platform instead — same DigitalOcean account, none of the server administration." }),
      b("heading", { text: "Go-live checklist", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Supabase connection string stored as an encrypted env var, not in code",
        "SSL certificate issued (Let's Encrypt via certbot on a Droplet; automatic on App Platform)",
        "Firewall configured if using a Droplet (ufw allow 80,443,22 only)",
        "Custom domain DNS pointed at the right A record or App Platform target",
      ] }),
      sources([
        link("https://www.digitalocean.com/pricing/droplets", "DigitalOcean Droplet Pricing"),
        link("https://www.digitalocean.com/pricing/app-platform", "DigitalOcean App Platform Pricing"),
        link("https://www.digitalocean.com/pricing/managed-databases", "DigitalOcean Managed Databases Pricing"),
        link("https://www.digitalocean.com/blog/dropletplans-persecbilling-byoip-natgateway", "DigitalOcean per-second billing announcement"),
        link("https://www.digitalocean.com/community/developer-center/deploying-a-next-js-application-on-a-digitalocean-droplet", "Deploying Next.js on a DigitalOcean Droplet"),
        link("https://supabase.com/pricing", "Supabase Pricing"),
      ]),
    ],
  },
];
