import { b, rich } from "./demo-blocks";
import { type GuideSeed, sources, link } from "./demo-guides-stacks-shared";

/** Stack-deploy guides, part B: Railway, Cloudflare Pages+D1, Hetzner+self-hosted Postgres. */
export const DEPLOY_B: GuideSeed[] = [
  {
    slug: "deploy-on-railway",
    title: "Deploy on Railway",
    data: {
      tagline: "The most beginner-friendly all-in-one — app and Postgres in the same dashboard",
      summary: "Fact-checked pricing, feasibility, and a full deploy walkthrough for Railway, including its Postgres template.",
      category: "own-your-stack",
      source_platform: "railway",
      target_platform: "",
      difficulty: "beginner",
      effort_hours_min: 1,
      effort_hours_max: 3,
      cost_min_usd: 5,
      cost_max_usd: 20,
      cost_period: "mo",
      tags: ["hosting", "database", "platform-evaluation"],
      resource_slugs: [],
      skills_required: ["Basic git"],
      requirements: ["A GitHub repo", "A credit card on file (required since March 2026)"],
    },
    blocks: [
      b("heading", { text: "Deploy on Railway", level: "h1", align: "left" }),
      rich("<p>Railway is the closest thing to Heroku's old simplicity that's still around: app and database live in the same project canvas, deploy is git push or a CLI command, and adding Postgres is a couple of clicks. The tradeoff is usage-based pricing that needs watching, and a rockier 2025–2026 reliability record than the bigger players.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Free trial: a one-time $5 credit for new signups, expires in 30 days, no card required",
        "Hobby: $5/mo subscription, includes $5/mo of usage — you pay only the delta if you go over",
        "Pro: $20/mo subscription, includes $20/mo of usage",
        "Resource pricing beyond the included credit: RAM $10/GB/mo, CPU $20/vCPU/mo, egress $0.05/GB, volume storage $0.15/GB/mo",
        "A small Postgres instance often runs under $2/mo on Hobby credit; a heavier one can exceed it — one review found ~$18/mo for a non-trivial database",
        "As of March 30, 2026, Railway requires a card on file for post-paid billing — prepay-only accounts are no longer accepted for new signups",
      ] }),
      b("heading", { text: "Feasibility", level: "h2", align: "left" }),
      rich("<p>This is the easiest deploy in the whole set if you just want something running today. The tradeoff shows up later, in the usage-based bill and in reliability.</p>"),
      b("callout", { tone: "danger", title: "Reliability worth knowing about", body: "Railway had a rough stretch: a December 2025 cryptominer exploit (via a Next.js vulnerability) caused a fleet-wide ~4-hour outage; a February 2026 nine-wave DDoS plus a fiber cut caused multi-day intermittent disruption; and a May 2026 ~8-hour full-platform outage happened after Google Cloud suspended Railway's GCP account entirely, taking down dashboard, API, deployments, and databases together. None of this is disqualifying, but it's a real pattern to weigh against the convenience." }),
      b("heading", { text: "Deploy it", level: "h2", align: "left" }),
      rich("<p>Create a project, connect your GitHub repo (auto-deploys on push), then hit the + button or Cmd/Ctrl+K to add a Postgres database as a zero-config template — no separate purchase step, it's billed under the same usage model as your app.</p>"),
      b("code", { filename: "terminal", language: "bash", code: "npm i -g @railway/cli\nrailway login\nrailway link\nrailway up" }),
      b("callout", { tone: "tip", title: "Dockerfile support", body: "If a file literally named Dockerfile (capital D) sits at your repo root, Railway auto-detects and builds from it instead of its default builder. Docker Compose deploys are also supported directly." }),
      b("heading", { text: "Go-live checklist", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Usage dashboard checked so you know your baseline cost before scaling",
        "Custom domain added under Settings → Public Networking with the required CNAME and TXT records",
        "Database backup strategy in place — Railway's own status history is reason enough",
      ] }),
      sources([
        link("https://docs.railway.com/pricing/plans", "Railway Pricing Plans"),
        link("https://docs.railway.com/pricing/free-trial", "Railway Free Trial"),
        link("https://docs.railway.com/databases/postgresql", "Railway PostgreSQL docs"),
        link("https://docs.railway.com/builds/dockerfiles", "Railway Dockerfiles"),
        link("https://venturebeat.com/infrastructure/railway-secures-usd100-million-to-challenge-aws-with-ai-native-cloud", "VentureBeat: Railway raises $100M Series B"),
        link("https://northflank.com/blog/railway-app-outage", "Railway outage history"),
      ]),
    ],
  },
  {
    slug: "deploy-on-cloudflare-pages-and-d1",
    title: "Deploy on Cloudflare Pages + D1",
    data: {
      tagline: "The cheapest real stack here — unmetered bandwidth, a genuinely generous free tier",
      summary: "Fact-checked pricing, feasibility, and a full deploy walkthrough for Cloudflare Pages with D1, Cloudflare's edge SQLite database.",
      category: "own-your-stack",
      source_platform: "cloudflare-pages",
      target_platform: "cloudflare-d1",
      difficulty: "intermediate",
      effort_hours_min: 4,
      effort_hours_max: 8,
      cost_min_usd: 0,
      cost_max_usd: 5,
      cost_period: "mo",
      tags: ["hosting", "database", "platform-evaluation"],
      resource_slugs: [],
      skills_required: ["Comfortable with the command line", "Basic SQL"],
      requirements: ["A GitHub repo", "Wrangler CLI"],
    },
    blocks: [
      b("heading", { text: "Deploy on Cloudflare Pages + D1", level: "h1", align: "left" }),
      rich("<p>If cost is the deciding factor, this is the stack. Cloudflare doesn't charge for bandwidth anywhere in its pricing — static asset requests are free and unlimited on every plan — and D1's free tier (5 million row reads and 100,000 row writes a day) covers a genuinely large site. The tradeoff is a real edge-runtime learning curve: this isn't a drop-in Node deploy.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "Pages free: 500 builds/month, 1 concurrent build, 100 custom domains, unmetered bandwidth",
        "Pages Pro (part of the $5/mo Workers Paid plan): 5,000 builds/month, 5 concurrent builds",
        "D1 free: 5M row reads/day, 100K row writes/day, 5GB storage — resets daily at 00:00 UTC",
        "D1 paid (same $5/mo Workers Paid plan): 25 billion row reads/month included, then $0.001/million; 50 million row writes included, then $1.00/million",
        "No egress/bandwidth charges for D1 data access, ever",
      ] }),
      b("heading", { text: "Feasibility", level: "h2", align: "left" }),
      rich("<p>The pricing is the easy part — the deploy is the part that takes longer than it looks. Next.js needs an adapter (@opennextjs/cloudflare is the one Cloudflare is pushing toward) rather than deploying natively, and D1 isn't accessed directly from static pages — you need a Pages Function (which runs on the Workers runtime) to query it.</p>"),
      b("heading", { text: "Deploy it", level: "h2", align: "left" }),
      b("code", { filename: "terminal", language: "bash", code: "npm i -g wrangler\nwrangler login\nwrangler d1 create my-database\n# Add the returned database_id to wrangler.toml, then:\nwrangler pages deploy" }),
      b("code", { filename: "wrangler.toml", language: "toml", code: "[[d1_databases]]\nbinding = \"DB\"\ndatabase_name = \"my-database\"\ndatabase_id = \"<returned-id>\"" }),
      b("heading", { text: "Migrating existing data into D1", level: "h2", align: "left" }),
      rich("<p>D1 doesn't accept a raw SQLite file directly. Dump it to plain SQL, strip transaction wrappers, then import.</p>"),
      b("code", { filename: "terminal", language: "bash", code: "sqlite3 mydb.sqlite3 .dump > out.sql\n# remove BEGIN TRANSACTION / COMMIT lines from out.sql, then:\nwrangler d1 execute my-database --remote --file=out.sql" }),
      b("callout", { tone: "info", title: "Pages is being folded into Workers", body: "Cloudflare has said openly that Pages-specific features are being turned into general Workers features rather than maintained separately — Pages still works with no forced migration, but new capabilities (Secrets Store, Workflows, Containers) are Workers-only. Worth knowing before you build deep Pages-specific tooling." }),
      b("heading", { text: "Go-live checklist", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "D1 database bound correctly in wrangler.toml and confirmed reachable from a Pages Function",
        "Row-count check after import matches the source database",
        "Custom domain added — 100 per project on the free tier",
      ] }),
      sources([
        link("https://developers.cloudflare.com/pages/platform/limits/", "Cloudflare Pages limits"),
        link("https://developers.cloudflare.com/d1/platform/pricing/", "Cloudflare D1 pricing"),
        link("https://developers.cloudflare.com/pages/functions/pricing/", "Cloudflare Pages Functions pricing"),
        link("https://developers.cloudflare.com/d1/best-practices/import-export-data/", "D1 import and export data"),
        link("https://developers.cloudflare.com/workers/framework-guides/web-apps/nextjs/", "Next.js on Cloudflare Workers"),
        link("https://developers.cloudflare.com/workers/static-assets/migration-guides/migrate-from-pages/", "Migrate from Pages to Workers"),
      ]),
    ],
  },
  {
    slug: "deploy-on-hetzner-self-hosted-postgres",
    title: "Deploy on Hetzner + self-hosted Postgres",
    data: {
      tagline: "Maximum control, no third-party platform involved — and squarely advanced territory",
      summary: "Fact-checked pricing, honest feasibility read, and a full deploy walkthrough for a Hetzner VPS running self-hosted Postgres via a self-hosted PaaS layer.",
      category: "own-your-stack",
      source_platform: "hetzner",
      target_platform: "",
      difficulty: "advanced",
      effort_hours_min: 8,
      effort_hours_max: 16,
      cost_min_usd: 4,
      cost_max_usd: 15,
      cost_period: "mo",
      tags: ["hosting", "database", "requires-cli", "platform-evaluation"],
      resource_slugs: [],
      skills_required: ["SSH and Linux administration", "Firewall and networking basics", "Comfortable troubleshooting without a support ticket"],
      requirements: ["A domain you control", "Patience for a real ops learning curve"],
    },
    blocks: [
      b("heading", { text: "Deploy on Hetzner + self-hosted Postgres", level: "h1", align: "left" }),
      rich("<p>This is the only option in the set with zero third-party platform in the stack — just a server you rent and software you run. It's also the one every honest source agrees is advanced territory: SSH hardening, firewall rules, connection pooling, backups, and WAL archiving are all your job now. I'd only recommend it if you already have ops experience or your managed-database bill has climbed past roughly $150/month.</p>"),
      b("heading", { text: "What it costs", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "CX22 (shared vCPU): 2 vCPU, 4GB RAM, 40GB disk, 20TB traffic included, from €3.79/mo",
        "CPX22 (dedicated AMD): 2 vCPU, 4GiB RAM, 80GB SSD — rose to €7.99/mo in Germany/Finland as of April 2026",
        "A broad Hetzner price increase hit in June 2026 (CPX/CCX lines up 113–176%, CX line up 33–38%), driven by a DRAM shortage — applies to new orders, not existing contracts",
        "Bandwidth overage: €1/TB in EU/US regions after the included allowance",
        "Backups: budget separately — off-site S3-compatible storage for pg_dump archives is typically a few dollars a month extra",
      ] }),
      b("heading", { text: "Feasibility — read this honestly", level: "h2", align: "left" }),
      b("callout", { tone: "danger", title: "This is advanced, not intermediate", body: "Every credible source I checked places this in advanced territory for a reason: getting SSH hardening, firewall rules, PostgreSQL tuning, connection pooling, and WAL-based backups right is real work, and getting it wrong exposes your data to the entire internet. If you don't already have this experience, budget real learning time, not just setup time." }),
      b("heading", { text: "Deploy it", level: "h2", align: "left" }),
      rich("<p>Bare Docker Compose still works, but a self-hosted PaaS layer on top of the VPS has become the more commonly recommended approach in 2026 — it handles networking, SSL, and container orchestration for you. Coolify is the most established option (55K+ GitHub stars); Dokploy is the fastest-growing, lighter-weight alternative.</p>"),
      b("code", { filename: "terminal", language: "bash", code: "# Coolify one-line installer, run on a fresh Hetzner VPS\ncurl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash" }),
      b("code", { filename: "docker-compose.yml", language: "yaml", code: "services:\n  postgres:\n    image: postgres:17-alpine\n    restart: always\n    environment:\n      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}\n    ports:\n      - \"5432:5432\"\n    volumes:\n      - pgdata:/var/lib/postgresql/data\nvolumes:\n  pgdata:" }),
      b("callout", { tone: "warning", title: "Backups are not optional", body: "Set up pg_dump on a cron job pushing to off-site S3-compatible storage, or WAL-based point-in-time recovery, before you put real data on this. Note that pgBackRest was archived and is no longer maintained as of April 2026 — if you find a guide recommending it, look for a current alternative like WAL-G or a maintained tool instead." }),
      b("heading", { text: "Go-live checklist", level: "h2", align: "left" }),
      b("list", { style: "check", items: [
        "SSH key-only auth, password auth disabled",
        "Firewall (ufw or Hetzner Cloud Firewall) restricting Postgres port to trusted sources only",
        "Automated off-site backup tested with an actual restore, not just a successful-looking dump",
        "No crypto-adjacent workloads on the box — Hetzner bans mining and PoS validation fleet-wide and will terminate accounts over it",
      ] }),
      sources([
        link("https://www.hetzner.com/cloud/regular-performance", "Hetzner Cloud pricing"),
        link("https://docs.hetzner.com/general/infrastructure-and-availability/price-adjustment/", "Hetzner price adjustment, June 2026"),
        link("https://coolify.io/docs/knowledge-base/docker/compose", "Coolify Docker Compose docs"),
        link("https://www.bytebase.com/blog/top-open-source-postgres-backup-solution/", "Open-source Postgres backup solutions, 2026"),
        link("https://dev.to/alanwest/self-hosting-in-2026-what-is-actually-worth-running-yourself-2c0i", "Self-hosting in 2026: what's actually worth running yourself"),
        link("https://serveropsmasters.com/why-hetzner-banned-cryptocurrency-mining-what-it-means-for-cloud-users-storage-performance-and-compliance/", "Why Hetzner banned cryptocurrency mining"),
      ]),
    ],
  },
];
