import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { assertIdentifier } from "@/modules/content-schema/identifiers";

/**
 * Filesystem scaffolder — writes the "Next.js project structure" surface for a
 * published content type: real, checked-in route files at
 * `src/app/(public)/{base}/page.tsx` (index) and `{base}/[slug]/page.tsx`
 * (detail). Each is a THIN delegate to the shared ContentTypeIndex/
 * ContentTypeDetail renderers — same components the DB-driven router fallback
 * (router.ts) uses, so a type renders identically before and after scaffolding.
 *
 * Assumes a self-host writable FS (matches the deploy model). The router
 * fallback covers types before/without scaffolding; these files just make the
 * route a first-class part of the app tree.
 *
 * Cache Components rules baked into the generated files: `params` is awaited;
 * NO `export const dynamic`; NO `generateStaticParams`; the request-scoped body
 * is wrapped in `<Suspense fallback={null}>` with the fetch in an inner async
 * component — the marketplace `[type]/[slug]` idiom.
 */

/** The `(public)` route root — where a type's `{base}/…` folder is written. */
const PUBLIC_ROOT = path.join(process.cwd(), "src", "app", "(public)");

/**
 * Normalize a validated base to its single URL segment. The base is a
 * single-segment path (e.g. "/products" or "products"); a stray leading slash
 * is stripped and the result is asserted as a safe identifier so it can never
 * escape the routes directory.
 */
export function baseSegment(base: string): string {
  const segment = base.replace(/^\/+/, "").split("/").filter(Boolean)[0] ?? "";
  return assertIdentifier(segment);
}

/** Source of the generated index route file (`{base}/page.tsx`). */
export function indexRouteSource(slug: string): string {
  const s = JSON.stringify(slug);
  return `// AUTO-GENERATED by scaffoldTypeRoutes (modules/content-pages/scaffold.ts).
// Thin delegate to the shared content-type index renderer. Do not edit by hand;
// it is rewritten on publish and removed when the type is unpublished/deleted.
import { Suspense } from "react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getPublishedTypeByBase } from "@/modules/content-schema/queries";
import { ContentTypeIndex } from "@/modules/content-pages/public/ContentTypeIndex";
import { getGeneralSettings } from "@/modules/settings/queries";

const SLUG = ${s};

export async function generateMetadata(): Promise<Metadata> {
  const type = await getPublishedTypeByBase(\`/\${SLUG}\`);
  if (!type) return {};
  const general = await getGeneralSettings();
  return {
    title: \`\${type.pluralName || type.name} · \${general.name}\`,
    robots: general.indexable ? undefined : { index: false, follow: false },
  };
}

export default function Page() {
  return (
    <Suspense fallback={null}>
      <Inner />
    </Suspense>
  );
}

async function Inner() {
  const type = await getPublishedTypeByBase(\`/\${SLUG}\`);
  if (!type) notFound();
  return <ContentTypeIndex type={type} />;
}
`;
}

/** Source of the generated detail route file (`{base}/[slug]/page.tsx`). */
export function detailRouteSource(slug: string): string {
  const s = JSON.stringify(slug);
  return `// AUTO-GENERATED by scaffoldTypeRoutes (modules/content-pages/scaffold.ts).
// Thin delegate to the shared content-type detail renderer. Do not edit by hand;
// it is rewritten on publish and removed when the type is unpublished/deleted.
import { Suspense } from "react";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getPublishedTypeByBase, getPublishedTypeRow } from "@/modules/content-schema/queries";
import { ContentTypeDetail } from "@/modules/content-pages/public/ContentTypeDetail";
import { getGeneralSettings } from "@/modules/settings/queries";

const SLUG = ${s};

type Params = { slug: string };

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}): Promise<Metadata> {
  const { slug } = await params;
  const type = await getPublishedTypeByBase(\`/\${SLUG}\`);
  if (!type) return {};
  const row = await getPublishedTypeRow(type, slug);
  if (!row) return {};
  const general = await getGeneralSettings();
  const title = String(row[type.titleField ?? "title"] ?? "") || slug;
  return {
    title: \`\${title} · \${general.name}\`,
    robots: general.indexable ? undefined : { index: false, follow: false },
  };
}

export default function Page({ params }: { params: Promise<Params> }) {
  return (
    <Suspense fallback={null}>
      <Inner params={params} />
    </Suspense>
  );
}

async function Inner({ params }: { params: Promise<Params> }) {
  const { slug } = await params;
  const type = await getPublishedTypeByBase(\`/\${SLUG}\`);
  if (!type) notFound();
  const row = await getPublishedTypeRow(type, slug);
  if (!row) notFound();
  return <ContentTypeDetail type={type} row={row} />;
}
`;
}

/** Directory that holds a type's generated route files. */
function typeDir(segment: string): string {
  return path.join(PUBLIC_ROOT, segment);
}

/**
 * Write the two route files for a content type. `base` is the (validated)
 * single-segment base path; `slug` is the type's slug (used to look the type up
 * at request time). Idempotent — overwrites existing files.
 */
export async function scaffoldTypeRoutes(base: string, slug: string): Promise<void> {
  const segment = baseSegment(base);
  const dir = typeDir(segment);
  await mkdir(path.join(dir, "[slug]"), { recursive: true });
  await writeFile(path.join(dir, "page.tsx"), indexRouteSource(slug), "utf8");
  await writeFile(path.join(dir, "[slug]", "page.tsx"), detailRouteSource(slug), "utf8");
}

/** Remove a content type's generated route folder (used on unpublish/delete). */
export async function removeTypeRoutes(base: string): Promise<void> {
  const segment = baseSegment(base);
  await rm(typeDir(segment), { recursive: true, force: true });
}
