export const sql = `
ALTER TABLE projects ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS og_image TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS canonical_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS no_index INTEGER NOT NULL DEFAULT 0;

ALTER TABLE pages ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_image TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS canonical_url TEXT;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS no_index INTEGER NOT NULL DEFAULT 0;
`;
