import "server-only";
import { randomBytes } from "node:crypto";

/**
 * Typed wrappers over Supabase's Management API — verified endpoint shapes
 * (see the OAuth-first-connect plan for sourcing): `Authorization: Bearer
 * <token>` works identically for OAuth access tokens and PATs.
 *
 * IMPORTANT: `createProject`'s `dbPass` is ALWAYS generated by our own code
 * via `node:crypto.randomBytes`, never accepted from or generated by
 * Supabase — this is what lets "create a new project" be genuinely
 * zero-credential-entry, since we capture the password in the same request
 * that mints it. Supabase's Management API can never retrieve a project's
 * database password after the fact, under any auth method — a hard
 * platform constraint, not a design choice.
 */

const API_BASE = "https://api.supabase.com/v1";

async function managementFetch<T>(
  accessToken: string,
  path: string,
  init?: RequestInit,
): Promise<T> {
  const res = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: {
      authorization: `Bearer ${accessToken}`,
      "content-type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    throw new Error(`Supabase Management API ${path} failed: ${res.status} ${await res.text()}`);
  }
  return (await res.json()) as T;
}

export type SupabaseProjectSummary = {
  id: string;
  organization_id: string;
  name: string;
  region: string;
  status: string;
};

/** GET /v1/projects — every project the token's account/org can access. */
export async function listProjects(accessToken: string): Promise<SupabaseProjectSummary[]> {
  return managementFetch<SupabaseProjectSummary[]>(accessToken, "/projects");
}

/** GET /v1/projects/{ref} — single project detail (region, status). */
export async function getProject(accessToken: string, ref: string): Promise<SupabaseProjectSummary> {
  return managementFetch<SupabaseProjectSummary>(accessToken, `/projects/${ref}`);
}

export type SupabaseOrganizationSummary = { id: string; name: string };

/**
 * GET /v1/organizations — needed so "Create a new database" can offer an
 * organization to create the project under (POST /v1/projects requires
 * organization_id). Same typed-wrapper shape as listProjects/getProject.
 */
export async function listOrganizations(accessToken: string): Promise<SupabaseOrganizationSummary[]> {
  return managementFetch<SupabaseOrganizationSummary[]>(accessToken, "/organizations");
}

/** Generates a database password ourselves — Supabase never sees or picks this ahead of time. */
export function generateDbPassword(): string {
  // 24 random bytes, base64url — long, URL-safe, no padding characters that
  // would need extra escaping when later embedded in a connection string.
  return randomBytes(24).toString("base64url");
}

export type CreateProjectInput = {
  name: string;
  organizationId: string;
  region: string;
  /** Generated by generateDbPassword() — never by Supabase. */
  dbPass: string;
};

/**
 * POST /v1/projects — project creation is asynchronous: the response
 * carries project metadata (including `ref`) but the project is not
 * immediately ready for connections. Callers that need to query it should
 * poll `getProject`/testConnection rather than assuming instant availability.
 */
export async function createProject(
  accessToken: string,
  input: CreateProjectInput,
): Promise<SupabaseProjectSummary> {
  return managementFetch<SupabaseProjectSummary>(accessToken, "/projects", {
    method: "POST",
    body: JSON.stringify({
      name: input.name,
      organization_id: input.organizationId,
      region: input.region,
      db_pass: input.dbPass,
    }),
  });
}
